baseURL         = "https://www.snhusbc.com"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = ""
  subtitle    = ""
cover       = "pins.jpg"
  description = "SNHUSBC"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = "SouthernNewHampshireUSBC"
  githubName = ""

  logjpgo = ""
  orgName = ""
  orgWebsite = ""
  orgDescription = ""

  author = "SNHUSBC"
  authorAvatar = "snhusbc.jpg"
  authorLocation = "Southern Newhampshire"
  authorWebsite = ""
  authorDescription = ""

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Main"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Tournaments"
  url = "/categories/tournaments/"
  weight = 100

[[menu.main]]
  name = "News"
  url = "/categories/news/"
  weight = 99

[[menu.main]]
  name = "Honor Scores"
  url = "/categories/scores"
  weight = 95

  [[menu.main]]
  name = "Bylaws"
  url = "/categories/bylaws"
  weight = 90

  [[menu.main]]
  name = "Board Members"
  url = "/categories/board_members"
  weight = 88

  [[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 85